AWSTemplateFormatVersion: '2010-09-09'
Description: 'SoleMate CloudWatch Alarms and SNS Topics'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'production'
    Description: Environment name prefix

  AlertEmail:
    Type: String
    Description: Email address for critical alerts

  SlackWebhookURL:
    Type: String
    NoEcho: true
    Description: Slack webhook URL for notifications

Resources:
  # SNS Topics for Alerting
  CriticalAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${EnvironmentName}-critical-alarms
      DisplayName: SoleMate Critical Alarms

  WarningAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${EnvironmentName}-warning-alarms
      DisplayName: SoleMate Warning Alarms

  # Email Subscription for Critical Alarms
  CriticalAlarmsEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref CriticalAlarmsTopic
      Endpoint: !Ref AlertEmail

  # Lambda Function for Slack Notifications
  SlackNotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${EnvironmentName}-slack-notifications
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt SlackNotificationRole.Arn
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookURL
      Code:
        ZipFile: |
          import json
          import urllib3
          import os

          def lambda_handler(event, context):
              webhook_url = os.environ['SLACK_WEBHOOK_URL']

              message = json.loads(event['Records'][0]['Sns']['Message'])
              alarm_name = message['AlarmName']
              alarm_description = message['AlarmDescription']
              new_state = message['NewStateValue']
              reason = message['NewStateReason']

              color = '#FF0000' if new_state == 'ALARM' else '#00FF00'

              slack_message = {
                  'attachments': [{
                      'color': color,
                      'title': f'🚨 {alarm_name}',
                      'text': f'{alarm_description}\n*Status:* {new_state}\n*Reason:* {reason}',
                      'footer': 'SoleMate Monitoring',
                      'ts': int(context.aws_request_id)
                  }]
              }

              http = urllib3.PoolManager()
              response = http.request(
                  'POST',
                  webhook_url,
                  body=json.dumps(slack_message),
                  headers={'Content-Type': 'application/json'}
              )

              return {'statusCode': 200}

  SlackNotificationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # SNS Subscription for Slack Lambda
  SlackNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn: !Ref CriticalAlarmsTopic
      Endpoint: !GetAtt SlackNotificationFunction.Arn

  # Permission for SNS to invoke Lambda
  SlackNotificationInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SlackNotificationFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref CriticalAlarmsTopic

  # Application Load Balancer Alarms
  ALBHighLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ALB-HighLatency
      AlarmDescription: ALB response time is too high
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 2.0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Sub app/${EnvironmentName}-ALB
      AlarmActions:
        - !Ref CriticalAlarmsTopic

  ALBHighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ALB-HighErrorRate
      AlarmDescription: ALB 5xx error rate is too high
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Sub app/${EnvironmentName}-ALB
      AlarmActions:
        - !Ref CriticalAlarmsTopic

  # ECS Service Alarms
  ECSHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ECS-HighCPU
      AlarmDescription: ECS CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: solemate-backend
        - Name: ClusterName
          Value: !Sub ${EnvironmentName}-cluster
      AlarmActions:
        - !Ref WarningAlarmsTopic

  ECSHighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ECS-HighMemory
      AlarmDescription: ECS memory utilization is too high
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: solemate-backend
        - Name: ClusterName
          Value: !Sub ${EnvironmentName}-cluster
      AlarmActions:
        - !Ref WarningAlarmsTopic

  ECSTaskCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ECS-LowTaskCount
      AlarmDescription: ECS running task count is too low
      MetricName: RunningTaskCount
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: solemate-backend
        - Name: ClusterName
          Value: !Sub ${EnvironmentName}-cluster
      AlarmActions:
        - !Ref CriticalAlarmsTopic

  # RDS Database Alarms
  RDSHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-RDS-HighCPU
      AlarmDescription: RDS CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 75
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${EnvironmentName}-postgres
      AlarmActions:
        - !Ref WarningAlarmsTopic

  RDSHighConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-RDS-HighConnections
      AlarmDescription: RDS connection count is too high
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${EnvironmentName}-postgres
      AlarmActions:
        - !Ref WarningAlarmsTopic

  RDSLowFreeMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-RDS-LowFreeMemory
      AlarmDescription: RDS free memory is too low
      MetricName: FreeableMemory
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 268435456  # 256MB in bytes
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${EnvironmentName}-postgres
      AlarmActions:
        - !Ref CriticalAlarmsTopic

  # Redis Cache Alarms
  RedisHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-Redis-HighCPU
      AlarmDescription: Redis CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 75
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: CacheClusterId
          Value: !Sub ${EnvironmentName}-redis
      AlarmActions:
        - !Ref WarningAlarmsTopic

  RedisHighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-Redis-HighMemory
      AlarmDescription: Redis memory utilization is too high
      MetricName: DatabaseMemoryUsagePercentage
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: CacheClusterId
          Value: !Sub ${EnvironmentName}-redis
      AlarmActions:
        - !Ref WarningAlarmsTopic

  # Custom Application Metrics Alarms
  HighPaymentFailureRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-HighPaymentFailureRate
      AlarmDescription: Payment failure rate is too high
      MetricName: PaymentFailureRate
      Namespace: SoleMate/Business
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5  # 5% failure rate
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref CriticalAlarmsTopic

  LowOrderVolumeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-LowOrderVolume
      AlarmDescription: Order volume is unusually low
      MetricName: OrdersPerMinute
      Namespace: SoleMate/Business
      Statistic: Average
      Period: 900  # 15 minutes
      EvaluationPeriods: 2
      Threshold: 0.1  # Less than 0.1 orders per minute
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref WarningAlarmsTopic

Outputs:
  CriticalAlarmsTopic:
    Description: SNS Topic for Critical Alarms
    Value: !Ref CriticalAlarmsTopic
    Export:
      Name: !Sub ${EnvironmentName}-CriticalAlarmsTopic

  WarningAlarmsTopic:
    Description: SNS Topic for Warning Alarms
    Value: !Ref WarningAlarmsTopic
    Export:
      Name: !Sub ${EnvironmentName}-WarningAlarmsTopic